### ISSUE TITLE
Sleep data Nowatch in hours or minutes? 

### ISSUE THREAD

**Issue by luciennedenuil** [PCdLf/wearalyze#17]
Hi @hypebright,

the Nowatch data from august 2024 I used:

[Nowatch all data august.zip](https://github.com/user-attachments/files/17774872/Nowatch.all.data.august.zip)

**Comment by hypebright** [comment]
@luciennedenuil with the latest update, this should be fixed. So you can pull and try again :). 

For some reason with your data the difference between start time and end time was recorded in minutes, and not in hours. I put in something extra that it always forces to hours.

This is the result now in the graph:

<img width="672" alt="image" src="https://github.com/user-attachments/assets/dcb0f01d-1471-461d-b2a5-7d0c3262737d">

**Comment by luciennedenuil** [comment]
Hi guys,

My sleep data from august looks like this:

![Schermopname_3-12-2024_135150_127 0 0 1](https://github.com/user-attachments/assets/2f854d04-6e66-48c5-adfc-5b137ca3f8f0)
