### ISSUE TITLE
Issue downloading rprojroot package after using renv :: restore ()

### ISSUE THREAD

**Issue by isabellatangorra** [PCdLf/wearalyze#8]
When I open the wearalyze.Rproj  and run renv :: restore () the packages download but failes when it reaches “rprojroot”. The error looks like this:
_- Installing rprojroot ...                      FAILED
Error in if (cond) return(expr) : the condition has length > 1
In addition: Warning message:
In system2(R(), args, stdout = TRUE, stderr = TRUE) :
  running command ''/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/bin/R' CMD config CC 2>&1' had status 1_

After this, I also get an error when running the app and trying to install Rhino. With both I get the same error:
_- Installing digest ...                         FAILED
Traceback (most recent calls last):
15: .rs.sourceWithProgress(script = "/var/folders/hg/3h5_xg5s50502dz2c8vll47c0000gn/T/d657-6e07-ce09-cbaa", 
        encoding = "UTF-8", con = stdout(), importRdata = NULL, exportRdata = NULL)
14: eval(statements[[idx]], envir = globalenv())
13: eval(statements[[idx]], envir = globalenv())
12: renv::install("digest")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: renv_scope_install()
 2: renv_scope_install_macos(scope)
 1: case(matches("/usr/bin/clang") ~ TRUE, matches("clang") ~ Sys.which("clang") == 
        "/usr/bin/clang", FALSE)
Error in if (cond) return(expr) : the condition has length > 1
Calls: .rs.sourceWithProgress ... renv_scope_install -> renv_scope_install_macos -> case
In addition: Warning message:
In system2(R(), args, stdout = TRUE, stderr = TRUE) :
  running command ''/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/bin/R' CMD config CC 2>&1' had status 1
Execution halted_

I’m not sure how to troubleshoot this…

**Comment by PCdLf** [comment]
Isabella is no longer working on this project, so probably not relevant anymore.
